apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
        - name: poc-container
          image: harikapilli/testharika:latest1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: poc-service
  namespace: default
spec:
  selector:
    app: poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


