name: Docker Image CI

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:
    inputs:
      docker-image-name:
        description: 'Docker Image Name'
        required: true
        default: 'test11111'
      docker-tag:
        description: 'Docker Tag'
        required: true
        default: 'latest1'

jobs:
  build-war-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ github.event.inputs.docker-image-name || 'default-image-name' }}
      DOCKER_TAG: ${{ github.event.inputs.docker-tag || 'latest' }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Java Maven
        run: |
          java -version
          mvn -version
      - name: Build with Maven
        run: mvn clean install
      - name: file copy
        run: |
          cp /home/runner/work/docker_build/docker_build/webapp/target/webapp.war .
          ls -ltr
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:$DOCKER_TAG
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag the Docker image
        run: docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG
      - name: Push the Docker image
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG
      - name: show images
        run: |
          docker images
      - name: Docker Hub Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push to Docker Hub
        run: docker push harikapilli/githubactions:${DOCKER_TAG}

      - name: Show Docker images
        run: docker images
